# Generated by Django 4.0.1 on 2022-07-04 22:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngerExp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INECoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LegalBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeinPlataform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViolenceCriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVariables',
            fields=[
                ('customer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('housing_time', models.CharField(max_length=200, null=True)),
                ('housing_mates', models.CharField(max_length=300, null=True)),
                ('housing_type', models.CharField(max_length=300, null=True)),
                ('eco_dependents', models.CharField(max_length=300, null=True)),
                ('prev_occupation', models.CharField(max_length=200, null=True)),
                ('other_source_income', models.BooleanField(null=True)),
                ('registered_time', models.CharField(max_length=200, null=True)),
                ('driving_time', models.CharField(max_length=200, null=True)),
                ('plat_score', models.FloatField(null=True)),
                ('anger_mgmt', models.IntegerField(null=True)),
                ('default_tendency', models.IntegerField(null=True)),
                ('strong_words', models.IntegerField(null=True)),
                ('time_effort_inv', models.IntegerField(null=True)),
                ('quick_anger', models.IntegerField(null=True)),
                ('keeping_objs', models.IntegerField(null=True)),
                ('steal_tendency', models.IntegerField(null=True)),
                ('get_job_done', models.IntegerField(null=True)),
                ('unconcerned', models.IntegerField(null=True)),
                ('unthink_tendency', models.IntegerField(null=True)),
                ('lie_tendency', models.IntegerField(null=True)),
                ('disregard_tendency', models.IntegerField(null=True)),
                ('enjoys_adrenaline', models.IntegerField(null=True)),
                ('enjoys_fast_driving', models.IntegerField(null=True)),
                ('drives_fast', models.IntegerField(null=True)),
                ('took_time_respond', models.BooleanField(null=True)),
                ('stable_profile', models.IntegerField(null=True)),
                ('pasive_agresive_profile', models.IntegerField(null=True)),
                ('impulsive_profile', models.IntegerField(null=True)),
                ('INE_coincidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.inecoin')),
                ('anger_exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.angerexp')),
                ('earnings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.earnings')),
                ('edu_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.edulevel')),
                ('legal_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.legalback')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.maritalstatus')),
                ('plat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.typeinplataform')),
                ('vio_criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.violencecriteria')),
            ],
        ),
    ]
