# Generated by Django 4.0.1 on 2022-07-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_drivingtime_ecodependents_housemates_housingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevariables',
            name='driving_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.drivingtime'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='eco_dependents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.ecodependents'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='housing_mates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.housemates'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='housing_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.housingtime'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='housing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.housingtype'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='prev_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.prevoccupation'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='registered_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.platregisttime'),
        ),
    ]
