# Generated by Django 4.0.1 on 2022-08-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_profilevariables_driving_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='other_source_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.otherincome'),
        ),
        migrations.AlterField(
            model_name='profilevariables',
            name='took_time_respond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.lateresponse'),
        ),
    ]
