# Generated by Django 4.0.1 on 2022-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_profilevariables_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtime',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ecodependents',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housingtime',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platregisttime',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
