# Generated by Django 4.0.1 on 2022-09-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_drivingtime_value_ecodependents_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angerexp',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='earnings',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='edulevel',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housemates',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housingtype',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inecoin',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lateresponse',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalback',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maritalstatus',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prevoccupation',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='typeinplataform',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='violencecriteria',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
