# Generated by Django 4.0.1 on 2022-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_angerexp_value_earnings_value_edulevel_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilevariables',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='customer_rfc',
            field=models.CharField(default='RFC0000', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
