# Generated by Django 4.0.1 on 2022-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_remove_profilevariables_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevariables',
            name='cat_activo',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='cat_devo',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='cat_repo',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='cat_robos',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='oc_no',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='oc_si',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='ts_asalto',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='ts_choque',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='ts_otro',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='ts_percance',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='ts_robo',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
