# Generated by Django 4.0.1 on 2022-09-09 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_profilevariables_cat_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilevariables',
            name='customer_rfc',
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
