# Generated by Django 4.0.1 on 2022-09-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_remove_profilevariables_customer_rfc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholIntake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrivenCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DUI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignTrips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeRise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastAccident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastDrive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawsuitMatter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OppArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatAccidents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatExit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHoursPrev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='adress_ine',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='adress_other',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='car_workshop_motive',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='carjacking_zone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='cc_mgmt',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='freq_states',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='multiplat_trips',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='plat_acc_motive',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='plat_score_motive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='re_entry',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='risk_before_acc',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='states',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='tax_stamps',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='tax_stamps_loaded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='alcohol_intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.alcoholintake'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='driven_car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.drivencar'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='dui',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.dui'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='foreign_trips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.foreigntrips'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='income_expectations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.incomeexp'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='income_rise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.incomerise'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='last_accident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.lastaccident'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='last_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.lastdrive'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='last_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.lastincome'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='lawsuit_matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.lawsuitmatter'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='monthly_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.monthlyexpenses'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='opp_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.opparea'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.parking'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='plat_accidents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.plataccidents'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='plat_exit_motive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.platexit'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='plataform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.plataform'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.questionnaire'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='working_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.workinghours'),
        ),
        migrations.AddField(
            model_name='profilevariables',
            name='working_hours_prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.workinghoursprev'),
        ),
    ]
