# Generated by Django 4.0.1 on 2022-09-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_alcoholintake_drivencar_dui_foreigntrips_incomeexp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilevariables',
            old_name='risk_before_acc',
            new_name='risk_before_accu',
        ),
    ]
