# Generated by Django 4.0.1 on 2022-09-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_adressine_multiplataform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressIne',
            new_name='AddressIne',
        ),
        migrations.RenameField(
            model_name='profilevariables',
            old_name='adress_ine',
            new_name='address_ine',
        ),
        migrations.RenameField(
            model_name='profilevariables',
            old_name='adress_other',
            new_name='address_other',
        ),
    ]
