# Generated by Django 4.0.1 on 2022-09-19 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zavic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='customer_rfc',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
