# Generated by Django 4.0.1 on 2022-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavic', '0004_alter_answer_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
