# Generated by Django 4.0.1 on 2022-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavic', '0005_answer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='corrupt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='indifferent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='legal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='moral',
            field=models.IntegerField(null=True),
        ),
    ]
